# プロジェクト名
name: joppy2
# バンドルID
options:
  # バンドルプレフィックス
  bundleIdPrefix: joppy2
  # LocalizationsのDevelopment Languageを指定
  developmentLanguage: ja
  
# firebaseの設定
packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk
    from: 10.21.0
  
# ターゲットごとの設定
targets:
  joppy2:
    # ターゲットの製品タイプ
    type: application
    # ターゲットのプラットフォーム
    platform: iOS
    # デプロイメントターゲット
    deploymentTarget: "16.0"
    #採用するfirebaseのサービス
    dependencies:
      - package: Firebase
        product: FirebaseAuth
      - package: Firebase
        product: FirebaseFirestore
      - package: Firebase
        product: FirebaseStorage
      - package: Firebase
        product: FirebaseFirestoreSwift
      
    sources:
      - joppy2
      - project.yml
      - .gitignore
      - .swiftlint.yml
      - .swift-version
      
    settings:
      base:
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        DEVELOPMENT_TEAM: chanchrons
        OTHER_LDFLAGS:
          - $(inherited)
          - -ObjC
          - -all_load

    info:
      path: joppy2/Info.plist
      properties:
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        LSRequiresIPhoneOS: YES
        UILaunchScreen: ""
        UIApplicationSupportsIndirectInputEvents: YES
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: YES
        UISupportedInterfaceOrientations~iphone:
          [UIInterfaceOrientationPortrait, UIInterfaceOrientationLandscapeLeft, UIInterfaceOrientationLandscapeRight]
        UISupportedInterfaceOrientations~ipad:
          [UIInterfaceOrientationPortrait, UIInterfaceOrientationPortraitUpsideDown, UIInterfaceOrientationLandscapeLeft, UIInterfaceOrientationLandscapeRight]

  joppy2Tests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - joppy2Tests
    settings:
      base:
        INFO_PLIST_FILE: joppy2Tests/Info.plist
    dependences:
      - target: joppy2
        
  joppy2UITests:
    type: bundle.ui-testing
    platform: iOS
    sources: joppy2UITests
    settings:
      base:
        INFOPLIST_FILE: joppy2UITests/Info.plist
    dependencies:
      - target: joppy2
